services:
    webgps:
        build: .
        container_name: gnss-frontend
        restart: always
        environment:
            - NGINX_PORT=${NGINX_PORT}
            - SERVER_NAME=${SERVER_NAME}
        volumes:
            - .env:/app/.env
        ports:
            - "${APP_PORT}:${NGINX_PORT}"
        # depends_on:
        #     - backend
