# Generated by Django 5.0.4 on 2025-08-18 13:21

from django.db import migrations


def compute_visit_gnssdatafiles_size(apps, schema_editor):
    VisitGNSSDataFiles = apps.get_model('api', 'VisitGNSSDataFiles')

    for record in VisitGNSSDataFiles.objects.all():
        try:
            if record.file and hasattr(record.file, 'size'):
                # Convert bytes to human readable format
                size = record.file.size
                if size < 1024:
                    record.size = f"{size} B"
                elif size < 1024 * 1024:
                    record.size = f"{size / 1024:.1f} KB"
                elif size < 1024 * 1024 * 1024:
                    record.size = f"{size / (1024 * 1024):.1f} MB"
                else:
                    record.size = f"{size / (1024 * 1024 * 1024):.1f} GB"

            record.save()
        except FileNotFoundError:
            print(
                f"File not found for record ID {record.id}, skipping size computation.")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20250729_1806'),
    ]

    operations = [migrations.RunPython(compute_visit_gnssdatafiles_size)
                  ]
