# Generated by Django 5.0.4 on 2025-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20250818_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stacks',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='user',
            name='clustering_distance',
            field=models.IntegerField(default=10),
        ),
    ]
