# Generated by Django 5.0.4 on 2025-08-29 19:32

from django.db import migrations


def create_endpoints(apps, schema_editor):
    Endpoint = apps.get_model('api', 'Endpoint')
    api_routes = [
        ('/api/people/<PATH_PARAM>/relations', 'GET'),
        ('/api/remove-earthquakes-affected-stations-cache', 'POST'),
        ('/api/stations/<PATH_PARAM>/nearby-stations/<PATH_PARAM>', 'GET'),
        ('/api/station/<PATH_PARAM>/parse-station-info-by-file', 'POST'),
    ]
    for path, method in api_routes:
        Endpoint.objects.create(path=path, method=method)


def create_endpoints_clusters(apps, schema_editor):
    EndPointsCluster = apps.get_model('api', 'EndPointsCluster')
    Resource = apps.get_model('api', 'Resource')
    Endpoint = apps.get_model('api', 'Endpoint')
    ClusterType = apps.get_model('api', 'ClusterType')

    # get people relations
    overview_read = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='overview'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read')
    )
    overview_read.endpoints.add(
        Endpoint.objects.get(path="/api/people/<PATH_PARAM>/relations", method="GET"))

    overview_read_write = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='overview'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read-write')
    )

    overview_read_write.endpoints.add(
        Endpoint.objects.get(
            path="/api/people/<PATH_PARAM>/relations", method="GET")
    )

    # remove earthquake cache
    earthquakes_read = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='earthquakes'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read')
    )
    earthquakes_read.endpoints.add(
        Endpoint.objects.get(
            path="/api/remove-earthquakes-affected-stations-cache", method="POST")
    )

    # get nearby stations and parse station info file
    stations_read = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='stations'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read')
    )
    stations_read.endpoints.add(
        Endpoint.objects.get(
            path="/api/stations/<PATH_PARAM>/nearby-stations/<PATH_PARAM>", method="GET")
    )

    stations_read_create = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='stations'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read-create')
    )

    stations_read_create.endpoints.add(
        Endpoint.objects.get(
            path="/api/stations/<PATH_PARAM>/nearby-stations/<PATH_PARAM>", method="GET")
    )

    stations_read_write = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='stations'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read-write')
    )
    stations_read_write.endpoints.add(
        Endpoint.objects.get(
            path="/api/stations/<PATH_PARAM>/nearby-stations/<PATH_PARAM>", method="GET")
    )

    stations_read_write.endpoints.add(
        Endpoint.objects.get(
            path="/api/station/<PATH_PARAM>/parse-station-info-by-file", method="POST")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_stacks_options_alter_user_clustering_distance'),
    ]

    operations = [
        migrations.RunPython(create_endpoints),
        migrations.RunPython(create_endpoints_clusters),
    ]
