# Generated by Django 5.0.4 on 2025-09-01 13:35

from django.db import migrations


def create_endpoints(apps, schema_editor):
    Endpoint = apps.get_model('api', 'Endpoint')
    Endpoint.objects.create(
        path="/api/stations/<PATH_PARAM>/get-kmz", method="GET")


def edit_endpoints_clusters(apps, schema_editor):
    EndPointsCluster = apps.get_model('api', 'EndPointsCluster')
    Resource = apps.get_model('api', 'Resource')
    Endpoint = apps.get_model('api', 'Endpoint')
    ClusterType = apps.get_model('api', 'ClusterType')

    stations_read = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='stations'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read')
    )
    stations_read.endpoints.add(
        Endpoint.objects.get(path="/api/stations/<PATH_PARAM>/get-kmz", method="GET"))

    stations_read_create = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='stations'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read-create')
    )
    stations_read_create.endpoints.add(
        Endpoint.objects.get(path="/api/stations/<PATH_PARAM>/get-kmz", method="GET"))

    stations_read_write = EndPointsCluster.objects.get(
        resource=Resource.objects.get(name='stations'),
        role_type='FRONT AND API',
        cluster_type=ClusterType.objects.get(name='read-write')
    )
    stations_read_write.endpoints.add(
        Endpoint.objects.get(path="/api/stations/<PATH_PARAM>/get-kmz", method="GET"))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20250829_1932'),
    ]

    operations = [
        migrations.RunPython(create_endpoints),
        migrations.RunPython(edit_endpoints_clusters),
    ]
